// Tables that live in more than one place stay identical.
const test = require("node:test");
const assert = require("node:assert/strict");
const { render } = require("../tools/sync-shared.js");
const { config } = require("./helpers.js");

test("the live function's event tables match config/feeds.json (node tools/sync-shared.js)", () => {
  assert.equal(render().changed, false);
});

test("the bundled supabase-js is the version package.json pins (npm run vendor)", () => {
  const fs = require("node:fs");
  const path = require("node:path");
  const root = path.join(__dirname, "..");
  const pinned = require(path.join(root, "package.json")).devDependencies["@supabase/supabase-js"];
  const head = fs.readFileSync(path.join(root, "web", "vendor", "supabase.js"), "utf8").split("\n")[0];
  assert.equal(head, `/* @supabase/supabase-js ${pinned}: generated by tools/vendor.js; don't edit */`);
});

test("every team in the season config has a code, colour and Jolpica ids", () => {
  for (const [name, t] of Object.entries(config("season").teams)) {
    if (name.startsWith("_")) continue;
    assert.match(t.code, /^[A-Z]{3}$/, name);
    assert.match(t.color, /^#[0-9A-F]{6}$/i, name);
    assert.ok(t.jolpica.length, name);
  }
});
