// Bundles supabase-js (sign-in and settings sync) into web/vendor/supabase.js, which refresh.py inlines like the
// page's own scripts. The page used to import it from a CDN at run time; a copy built from the npm package (checked
// against package-lock.json's integrity hash) means no third-party script runs with the user's session.
// tests/shared.test.js fails if the copy and package.json's pinned version drift. Run:  npm run vendor
const fs = require("node:fs");
const path = require("node:path");
const esbuild = require("esbuild");

const ROOT = path.join(__dirname, "..");
const PKG = "@supabase/supabase-js";
const OUT = path.join(ROOT, "web", "vendor", "supabase.js");

const version = require(`${PKG}/package.json`).version;
const pinned = require(path.join(ROOT, "package.json")).devDependencies[PKG];
if (version !== pinned) throw new Error(`${PKG} ${version} is installed but package.json pins ${pinned}: run npm ci`);

const out = esbuild.buildSync({
  stdin: { contents: `export { createClient } from "${PKG}";`, resolveDir: ROOT },
  bundle: true,
  format: "iife",
  globalName: "supabase",
  platform: "browser",
  target: "es2020",
  minify: true,
  legalComments: "none",
  write: false,
});
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, `/* ${PKG} ${version}: generated by tools/vendor.js; don't edit */\n${out.outputFiles[0].text}`);
console.log(`${path.relative(ROOT, OUT)}: ${PKG} ${version}, ${Math.round(fs.statSync(OUT).size / 1024)} KB`);
